services:
  scraper:
    build:
      context: .
      target: base
    image: ticket-price-checker:latest
    container_name: ticket-price-checker
    command: ["bun", "run", "start"]
    environment:
      TZ: "Europe/Madrid"
      HEADLESS: true
    volumes:
      - .:/app